spring:
  application:
    name: onem-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/url_shortener?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000  # 5분
      max-lifetime: 1200000  # 20분
      connection-timeout: 20000  # 20초

block-domain:
  loader:
    file:
      name: hosts.txt
    source:
      url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    enable:
      jvm: true
      process: true
      http: true
      system: true
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 히스토그램 활성화

loki:
  endpoint: ${LOKI_ENDPOINT:http://localhost:3100/loki/api/v1/push}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {DB_ENDPOINT}

---
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {DB_ENDPOINT}

---
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {DB_ENDPOINT}
