spring:
  application:
    name: onem-backend

block-domain:
  loader:
    file:
      name: hosts.txt
    source:
      url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
