
### get origin url
GET http://localhost:8080/api/v1/shorten-url/U34ZpDV

### get origin url
GET http://localhost:8080/api/v1/shorten-url/{{$random.integer(10000)}}

### create shorten url
POST http://localhost:8080/api/v1/shorten-url
Content-Type: application/json

{
  "originalUrl": "https://example.com/{{$uuid}}"
}

### create shorten url (with expiration minutes)
POST http://localhost:8080/api/v1/shorten-url
Content-Type: application/json

{
  "originalUrl": "https://example.com/{{$uuid}}",
  "expirationMinutes": 10
}